### ISSUE TITLE
Laravel Sail - Add Minio Support?

### ISSUE THREAD

**Issue by riipandi** [laravel/ideas#2547]
Hi folks, sometimes we need to store uploaded files to S3 storage. Instead of using AWS S3 in local development, why not use Minio? Recently, I've already using Minio within Sail.

Perhaps this code snippet can help.

```yml
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER:-AKIAIOSFODNN7EXAMPLE}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}'
        volumes:
            - 'sailminio:/data/minio'
        networks:
            - sail
        command: minio server /data/minio
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3
```

For more information about Minio on Docker you can read here: <https://github.com/minio/minio/blob/master/docs/docker/README.md>

Thanks.
